python3 _ResNet50.py
python3 _CIFAR10_CNN.py
python3 _MNIST_CNN.py
python3 _InceptionV3.py
python3 _VGG16.py
python3 _InceptionResNetV2.py
python3 _LeNet5.py
python3 _ResNetSmall.py
python3 _MobileNetV2.py
python3 _AlexNet.py
