echo '_ResNet50'
python3 _ResNet50.py
echo '_CIFAR10_CNN'
python3 _CIFAR10_CNN.py
echo '_MNIST_CNN'
python3 _MNIST_CNN.py
echo '_InceptionV3'
python3 _InceptionV3.py
echo '_VGG16'
python3 _VGG16.py
echo '_InceptionResNetV2'
python3 _InceptionResNetV2.py
echo '_LeNet5'
python3 _LeNet5.py
echo '_ResNetSmall'
python3 _ResNetSmall.py
echo '_MobileNetV2'
python3 _MobileNetV2.py
echo '_AlexNet'
python3 _AlexNet.py
