echo '_InceptionResNetV2'
python3 _InceptionResNetV2.py
echo '_LeNet5'
python3 _LeNet5.py
echo '_ResNetSmall'
python3 _ResNetSmall.py
echo '_MobileNetV2'
python3 _MobileNetV2.py
echo '_AlexNet'
python3 _AlexNet.py
